/**
 * ESVA Blockchain Timestamp Proof
 * --------------------------------
 * Immutable timestamp proofs for calculation receipts.
 * MVP: Supabase hash registry (verifiable, auditable).
 * Future: Ethereum / Polygon on-chain anchoring.
 *
 * PART 1: Types
 * PART 2: Supabase hash registry (MVP proof layer)
 * PART 3: Proof verification
 * PART 4: Future chain integration stub
 */

import { getSupabaseAdmin } from '@/lib/supabase';
import { log } from '@/lib/logger';

// ─── PART 1: Types ────────────────────────────────────────────

export interface BlockchainProof {
  /** Transaction hash (Supabase row ID for MVP, tx hash for on-chain) */
  txHash: string;
  /** Block number (auto-increment row ID for MVP) */
  blockNumber: number;
  /** ISO-8601 timestamp when proof was recorded */
  timestamp: string;
  /** Chain identifier: 'esa-registry' for MVP, 'polygon' / 'ethereum' for future */
  chain: string;
  /** SHA-256 receipt hash being anchored */
  receiptHash: string;
  /** IPFS CID of the anonymized receipt */
  ipfsCid: string;
}

export interface ProofVerification {
  valid: boolean;
  timestamp: string;
  /** Reason if invalid */
  reason?: string;
}

// ─── PART 2: Supabase Hash Registry (MVP) ────────────────────

const PROOFS_TABLE = 'timestamp_proofs';
const MVP_CHAIN = 'esa-registry';

/**
 * Create a timestamp proof by recording receipt hash + IPFS CID
 * in the Supabase proof registry.
 *
 * This provides:
 * - Tamper-evident: Supabase row with server-generated timestamp
 * - Verifiable: Anyone can recompute hash and check against stored record
 * - Auditable: Full history of all notarized receipts
 */
export async function createTimestampProof(
  receiptHash: string,
  ipfsCid: string,
): Promise<BlockchainProof> {
  if (!receiptHash || typeof receiptHash !== 'string') {
    throw new Error('[ESA-6010] Invalid receiptHash: must be a non-empty string');
  }
  if (!ipfsCid || typeof ipfsCid !== 'string') {
    throw new Error('[ESA-6011] Invalid ipfsCid: must be a non-empty string');
  }

  const admin = getSupabaseAdmin();

  // Check for duplicate — same hash should return existing proof (idempotent)
  const { data: existing } = await admin
    .from(PROOFS_TABLE)
    .select('*')
    .eq('receipt_hash', receiptHash)
    .maybeSingle();

  if (existing) {
    return rowToProof(existing);
  }

  // Insert new proof record
  const { data, error } = await admin
    .from(PROOFS_TABLE)
    .insert({
      receipt_hash: receiptHash,
      ipfs_cid: ipfsCid,
      chain: MVP_CHAIN,
      // created_at is auto-generated by Supabase
    })
    .select('*')
    .single();

  if (error) {
    throw new Error(`[ESA-6012] Failed to create timestamp proof: ${error.message}`);
  }

  return rowToProof(data);
}

/**
 * Look up an existing proof by receipt hash.
 */
export async function getProofForReceipt(
  receiptHash: string,
): Promise<BlockchainProof | null> {
  if (!receiptHash) return null;

  const admin = getSupabaseAdmin();

  const { data, error } = await admin
    .from(PROOFS_TABLE)
    .select('*')
    .eq('receipt_hash', receiptHash)
    .maybeSingle();

  if (error) {
    throw new Error(`[ESA-6013] Failed to look up proof: ${error.message}`);
  }

  if (!data) return null;
  return rowToProof(data);
}

// ─── PART 3: Proof Verification ─────────────────────────────

/**
 * Verify a proof is genuine by checking the registry.
 *
 * Validation checks:
 * 1. Proof record exists in the registry
 * 2. Receipt hash matches
 * 3. IPFS CID matches
 * 4. Timestamp is consistent
 */
export async function verifyProof(
  proof: BlockchainProof,
): Promise<ProofVerification> {
  // For MVP registry: re-fetch from Supabase and compare
  if (proof.chain === MVP_CHAIN) {
    return verifyMvpProof(proof);
  }

  // Future chain verification would go here
  return {
    valid: false,
    timestamp: proof.timestamp,
    reason: `Unsupported chain: ${proof.chain}`,
  };
}

async function verifyMvpProof(proof: BlockchainProof): Promise<ProofVerification> {
  const admin = getSupabaseAdmin();

  const { data, error } = await admin
    .from(PROOFS_TABLE)
    .select('*')
    .eq('receipt_hash', proof.receiptHash)
    .maybeSingle();

  if (error || !data) {
    return {
      valid: false,
      timestamp: proof.timestamp,
      reason: 'Proof not found in registry',
    };
  }

  const stored = rowToProof(data);

  // Compare all critical fields
  if (stored.ipfsCid !== proof.ipfsCid) {
    return {
      valid: false,
      timestamp: stored.timestamp,
      reason: 'IPFS CID mismatch — possible tampering',
    };
  }

  if (stored.txHash !== proof.txHash) {
    return {
      valid: false,
      timestamp: stored.timestamp,
      reason: 'Transaction hash mismatch',
    };
  }

  return {
    valid: true,
    timestamp: stored.timestamp,
  };
}

// ─── PART 4: Future Chain Integration Stub ───────────────────

/**
 * Stub for future Ethereum/Polygon on-chain anchoring.
 * When enabled, this will:
 * 1. Batch receipt hashes into a Merkle root
 * 2. Submit root to a smart contract on Polygon
 * 3. Return tx hash + block number
 *
 * Not implemented for MVP — use Supabase registry.
 */
export async function anchorToChain(
  _receiptHashes: string[],
  _chain: 'ethereum' | 'polygon' = 'polygon',
): Promise<{ txHash: string; blockNumber: number; merkleRoot: string } | null> {
  // On-chain 앵커링은 Polygon registry 계약 배포 후 활성화.
  // 현재는 Supabase receipt 테이블 + SHA-256 해시로 무결성 보증.
  log.info('blockchain', 'On-chain anchoring deferred — using Supabase hash registry');
  return null;
}

// ─── Helpers ──────────────────────────────────────────────────

interface ProofRow {
  id: string;
  receipt_hash: string;
  ipfs_cid: string;
  chain: string;
  block_number?: number;
  created_at: string;
}

function rowToProof(row: ProofRow): BlockchainProof {
  return {
    txHash: row.id,
    blockNumber: row.block_number ?? 0,
    timestamp: row.created_at,
    chain: row.chain,
    receiptHash: row.receipt_hash,
    ipfsCid: row.ipfs_cid,
  };
}
