/**
 * YouTube Summary API Endpoint
 *
 * POST /api/youtube
 * Body: { url: string, language?: string, apiKey?: string, provider?: string }
 *
 * BYOK required for LLM summarization.
 * Returns YouTubeSummary with key points and related KEC clauses.
 *
 * PART 1: Validation
 * PART 2: Route handler
 */

import { applyRateLimit } from '@/lib/rate-limit';
import { NextRequest, NextResponse } from 'next/server';

// ---------------------------------------------------------------------------
// PART 1 -- Validation
// ---------------------------------------------------------------------------

interface YouTubeRequestBody {
  url: string;
  language?: string;
  apiKey?: string;
  provider?: 'openai' | 'anthropic' | 'google';
}

function isValidProvider(p: unknown): p is 'openai' | 'anthropic' | 'google' {
  return p === 'openai' || p === 'anthropic' || p === 'google';
}

// ---------------------------------------------------------------------------
// PART 2 -- Route handler
// ---------------------------------------------------------------------------

export async function POST(req: NextRequest): Promise<NextResponse> {
  try {

    const body = (await req.json()) as Partial<YouTubeRequestBody>;

    // --- Validation ---
    if (!body.url || typeof body.url !== 'string') {
      return NextResponse.json(
        { error: 'ESVA-6010: url is required' },
        { status: 400 },
      );
    }

    // Quick URL format check
    const { extractVideoId } = await import('@/lib/youtube-summary');
    const videoId = extractVideoId(body.url);
    if (!videoId) {
      return NextResponse.json(
        { error: 'ESVA-6011: Invalid YouTube URL. Supported formats: youtube.com/watch?v=, youtu.be/, youtube.com/shorts/' },
        { status: 400 },
      );
    }

    const language = body.language ?? 'ko';
    const provider = isValidProvider(body.provider) ? body.provider : 'openai';

    // API 키 없으면 자막만 가져오고 LLM 요약은 건너뜀
    if (!body.apiKey) {
      // BYOK 없이도 기본 정보는 반환
      const { fetchVideoMeta, fetchTranscript } = await import('@/lib/youtube-summary');

      try {
        const _meta = await fetchVideoMeta(videoId);
        const segments = await fetchTranscript(videoId, language);
        const transcriptText = segments.map((s) => s.text).join(' ');

        // KEC 감지만 수행 (LLM 불필요)
        const { summarizeYouTube } = await import('@/lib/youtube-summary');
        // apiKey 없이 호출하면 transcript만 사용
        const summary = await summarizeYouTube({
          url: body.url,
          lang: language,
        });

        return NextResponse.json({
          ...summary,
          note: 'API key not provided. Key points were not generated by LLM.',
          transcriptAvailable: transcriptText.length > 0,
          transcriptLength: transcriptText.length,
        });
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Unknown error';
        return NextResponse.json(
          { error: `ESA-6020: Failed to fetch video data: ${message}` },
          { status: 502 },
        );
      }
    }

    // --- Full summarization with BYOK ---
    try {
      const { summarizeYouTube } = await import('@/lib/youtube-summary');

      const summary = await summarizeYouTube({
        url: body.url,
        lang: language,
        apiKey: body.apiKey,
        provider,
      });

      return NextResponse.json(summary);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Unknown error';

      // LLM API 오류 구분
      if (message.includes('API error')) {
        return NextResponse.json(
          { error: `ESA-6030: LLM API error: ${message}` },
          { status: 502 },
        );
      }

      return NextResponse.json(
        { error: `ESA-6099: ${message}` },
        { status: 500 },
      );
    }
  } catch (err) {
    console.error('[YouTube API] Unhandled error:', err);
    const message = err instanceof Error ? err.message : 'Internal server error';
    return NextResponse.json(
      { error: `ESA-6099: ${message}` },
      { status: 500 },
    );
  }
}
