/**
 * ESVA Professional Engineering Disclaimer
 * -------------------------------------------
 * PE급 면책조항 + 공학적 불확실성 표시.
 * 모든 계산 결과 / 보고서에 첨부.
 *
 * PART 1: Disclaimer templates (multi-language)
 * PART 2: Uncertainty notation
 * PART 3: Professional review requirements
 */

// ═══════════════════════════════════════════════════════════════════════════════
// PART 1 — Disclaimer Templates
// ═══════════════════════════════════════════════════════════════════════════════

export interface ProfessionalDisclaimer {
  version: string;
  language: string;
  title: string;
  body: string[];
  legalNotice: string;
  peRequirement: string;
}

export const DISCLAIMERS: Record<string, ProfessionalDisclaimer> = {
  ko: {
    version: 'v4.0',
    language: 'ko',
    title: '전문가 면책조항 (Professional Disclaimer)',
    body: [
      '본 계산 결과는 ESVA 엔진에 의해 자동 생성된 참고용 자료이며, 최종 설계 판단을 대체하지 않습니다.',
      '모든 계산은 입력된 파라미터와 적용된 기준서(KEC/NEC/IEC)의 조건에 한정됩니다. 현장 조건(온도, 습도, 설치 방법, 기기 노후도 등)에 따라 실제 결과가 달라질 수 있습니다.',
      '아크플래시 에너지, 단락전류, 보호 협조 등 안전 관련 계산은 반드시 전문 소프트웨어(ETAP, SKM, EasyPower 등)로 재검증하십시오.',
      '본 시스템의 기준서 데이터는 참조용이며, 원문 확인은 해당 기준 발행 기관을 통해 수행해야 합니다.',
      'ESVA는 본 결과의 정확성, 완전성, 특정 목적 적합성에 대해 어떠한 보증도 하지 않습니다.',
    ],
    legalNotice: '본 결과를 인용하여 발생하는 설계 오류, 사고, 재산 피해에 대해 ESVA는 법적 책임을 지지 않습니다.',
    peRequirement: '최종 설계 도서에는 반드시 전기 분야 기술사(PE) 또는 자격을 갖춘 전문가의 검토·날인이 필요합니다.',
  },
  en: {
    version: 'v4.0',
    language: 'en',
    title: 'Professional Engineering Disclaimer',
    body: [
      'These calculations are generated by ESVA automated engines for reference purposes only and do not substitute professional engineering judgment.',
      'All calculations are limited to the entered parameters and applied standards (KEC/NEC/IEC). Actual results may vary depending on site conditions (temperature, humidity, installation method, equipment age, etc.).',
      'Safety-critical calculations such as arc flash energy, short circuit current, and protection coordination must be independently verified using professional-grade software (ETAP, SKM, EasyPower, etc.).',
      'Standard reference data in this system is for informational purposes. Original texts should be verified through the issuing standards body.',
      'ESVA makes no warranty regarding the accuracy, completeness, or fitness for any particular purpose of these results.',
    ],
    legalNotice: 'ESVA assumes no legal liability for design errors, incidents, or property damage arising from the use of these results.',
    peRequirement: 'Final design documents must be reviewed and stamped by a licensed Professional Engineer (PE) or equivalent qualified professional.',
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// PART 2 — Uncertainty Notation
// ═══════════════════════════════════════════════════════════════════════════════

export interface UncertaintyInfo {
  /** 계산값 불확실성 범위 (%) */
  tolerancePercent: number;
  /** 불확실성 원인 */
  sources: string[];
  /** 신뢰 수준 */
  confidenceLevel: 'high' | 'medium' | 'low';
  /** 권장 안전 여유 */
  recommendedMargin: number;
}

/** 계산기별 기본 불확실성 */
export const UNCERTAINTY: Record<string, UncertaintyInfo> = {
  'voltage-drop': {
    tolerancePercent: 2,
    sources: ['저항률 온도 의존성', '전선 길이 측정 오차', '부하전류 변동'],
    confidenceLevel: 'high',
    recommendedMargin: 1.15,
  },
  'cable-sizing': {
    tolerancePercent: 5,
    sources: ['설치 방법에 따른 보정계수', '주위 온도 가정', '전선 묶음 수'],
    confidenceLevel: 'medium',
    recommendedMargin: 1.25,
  },
  'short-circuit': {
    tolerancePercent: 10,
    sources: ['계통 임피던스 추정', '전원측 단락 용량', '변압기 임피던스 공차'],
    confidenceLevel: 'medium',
    recommendedMargin: 1.10,
  },
  'arc-flash': {
    tolerancePercent: 20,
    sources: ['IEEE 1584 경험식 한계', '전극 구성 가정', '아크 지속시간 추정'],
    confidenceLevel: 'low',
    recommendedMargin: 1.50,
  },
  'grounding': {
    tolerancePercent: 30,
    sources: ['토양 저항률 계절 변동', '접지봉 설치 깊이', '토양 수분 함량'],
    confidenceLevel: 'low',
    recommendedMargin: 1.50,
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// PART 3 — Professional Review Requirements
// ═══════════════════════════════════════════════════════════════════════════════

export interface ReviewRequirement {
  category: string;
  required: boolean;
  reviewer: string;
  reason: string;
}

/** 계산 유형별 전문가 검토 필요 여부 */
export const REVIEW_REQUIREMENTS: ReviewRequirement[] = [
  { category: 'arc-flash', required: true, reviewer: 'PE (전기)', reason: '안전 관련 — IEEE 1584 적합성 검증 필수' },
  { category: 'short-circuit', required: true, reviewer: 'PE (전기)', reason: '보호 협조 — 차단 용량 검증 필수' },
  { category: 'grounding', required: true, reviewer: 'PE (전기)', reason: '안전 관련 — 현장 측정 병행 필수' },
  { category: 'voltage-drop', required: false, reviewer: '전기 기사', reason: '설계 검증 — 서류 검토로 충분' },
  { category: 'cable-sizing', required: false, reviewer: '전기 기사', reason: '설계 검증 — 보정계수 확인' },
  { category: 'transformer', required: false, reviewer: '전기 기사', reason: '용량 산정 — 부하 데이터 확인' },
];

/** 면책조항 생성 */
export function getDisclaimer(language: string = 'ko'): ProfessionalDisclaimer {
  return DISCLAIMERS[language] ?? DISCLAIMERS['ko'];
}

/** 불확실성 정보 조회 */
export function getUncertainty(calculatorId: string): UncertaintyInfo | null {
  // 카테고리 추출 (voltage-drop-3phase → voltage-drop)
  const baseId = calculatorId.replace(/-3phase|-complex|-busbar|-country.*$/, '');
  return UNCERTAINTY[baseId] ?? null;
}

/** 전문가 검토 필요 여부 */
export function requiresPEReview(calculatorCategory: string): ReviewRequirement | null {
  return REVIEW_REQUIREMENTS.find(r => r.category === calculatorCategory) ?? null;
}
