/**
 * ESVA Professional Engineering Disclaimer
 * -------------------------------------------
 * PE급 면책조항 + 공학적 불확실성 표시.
 * 모든 계산 결과 / 보고서에 첨부.
 *
 * PART 1: Disclaimer templates (multi-language)
 * PART 2: Uncertainty notation
 * PART 3: Professional review requirements
 */

// ═══════════════════════════════════════════════════════════════════════════════
// PART 1 — Disclaimer Templates
// ═══════════════════════════════════════════════════════════════════════════════

export interface ProfessionalDisclaimer {
  version: string;
  language: string;
  title: string;
  body: string[];
  legalNotice: string;
  peRequirement: string;
}

export const DISCLAIMERS: Record<string, ProfessionalDisclaimer> = {
  ko: {
    version: 'v4.0',
    language: 'ko',
    title: '전문가 면책조항 (Professional Disclaimer)',
    body: [
      '본 계산 결과는 ESVA 엔진에 의해 자동 생성된 참고용 자료이며, 최종 설계 판단을 대체하지 않습니다.',
      '모든 계산은 입력된 파라미터와 적용된 기준서(KEC/NEC/IEC)의 조건에 한정됩니다. 현장 조건(온도, 습도, 설치 방법, 기기 노후도 등)에 따라 실제 결과가 달라질 수 있습니다.',
      '아크플래시 에너지, 단락전류, 보호 협조 등 안전 관련 계산은 반드시 전문 소프트웨어(ETAP, SKM, EasyPower 등)로 재검증하십시오.',
      '본 시스템의 기준서 데이터는 참조용이며, 원문 확인은 해당 기준 발행 기관을 통해 수행해야 합니다.',
      'ESVA는 본 결과의 정확성, 완전성, 특정 목적 적합성에 대해 어떠한 보증도 하지 않습니다.',
    ],
    legalNotice: '본 결과를 인용하여 발생하는 설계 오류, 사고, 재산 피해에 대해 ESVA는 법적 책임을 지지 않습니다.',
    peRequirement: '최종 설계 도서에는 반드시 전기 분야 기술사(PE) 또는 자격을 갖춘 전문가의 검토·날인이 필요합니다.',
  },
  en: {
    version: 'v4.0',
    language: 'en',
    title: 'Professional Engineering Disclaimer',
    body: [
      'These calculations are generated by ESVA automated engines for reference purposes only and do not substitute professional engineering judgment.',
      'All calculations are limited to the entered parameters and applied standards (KEC/NEC/IEC). Actual results may vary depending on site conditions (temperature, humidity, installation method, equipment age, etc.).',
      'Safety-critical calculations such as arc flash energy, short circuit current, and protection coordination must be independently verified using professional-grade software (ETAP, SKM, EasyPower, etc.).',
      'Standard reference data in this system is for informational purposes. Original texts should be verified through the issuing standards body.',
      'ESVA makes no warranty regarding the accuracy, completeness, or fitness for any particular purpose of these results.',
    ],
    legalNotice: 'ESVA assumes no legal liability for design errors, incidents, or property damage arising from the use of these results.',
    peRequirement: 'Final design documents must be reviewed and stamped by a licensed Professional Engineer (PE) or equivalent qualified professional.',
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// PART 2 — Uncertainty Notation
// ═══════════════════════════════════════════════════════════════════════════════

export interface UncertaintyInfo {
  /** 계산값 불확실성 범위 (%) */
  tolerancePercent: number;
  /** 불확실성 원인 */
  sources: string[];
  /** 신뢰 수준 */
  confidenceLevel: 'high' | 'medium' | 'low';
  /** 권장 안전 여유 */
  recommendedMargin: number;
}

/** 계산기별 기본 불확실성 */
export const UNCERTAINTY: Record<string, UncertaintyInfo> = {
  'voltage-drop': {
    tolerancePercent: 2,
    sources: ['저항률 온도 의존성', '전선 길이 측정 오차', '부하전류 변동'],
    confidenceLevel: 'high',
    recommendedMargin: 1.15,
  },
  'cable-sizing': {
    tolerancePercent: 5,
    sources: ['설치 방법에 따른 보정계수', '주위 온도 가정', '전선 묶음 수'],
    confidenceLevel: 'medium',
    recommendedMargin: 1.25,
  },
  'short-circuit': {
    tolerancePercent: 10,
    sources: ['계통 임피던스 추정', '전원측 단락 용량', '변압기 임피던스 공차'],
    confidenceLevel: 'medium',
    recommendedMargin: 1.10,
  },
  'arc-flash': {
    tolerancePercent: 20,
    sources: ['IEEE 1584 경험식 한계', '전극 구성 가정', '아크 지속시간 추정'],
    confidenceLevel: 'low',
    recommendedMargin: 1.50,
  },
  'grounding': {
    tolerancePercent: 30,
    sources: ['토양 저항률 계절 변동', '접지봉 설치 깊이', '토양 수분 함량'],
    confidenceLevel: 'low',
    recommendedMargin: 1.50,
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// PART 3 — Professional Review Requirements
// ═══════════════════════════════════════════════════════════════════════════════

export interface ReviewRequirement {
  category: string;
  required: boolean;
  reviewer: string;
  reason: string;
}

/** 계산 유형별 전문가 검토 필요 여부 */
/**
 * 검토 요구 표.
 *
 * **키가 id 와 category 를 섞어 쓴다**(2026-07-28 확인). 인자 이름은
 * `calculatorCategory` 인데 `arc-flash`·`short-circuit`·`cable-sizing` 은
 * 계산기 **id** 이고, 레지스트리에서 앞의 둘은 category 가 `protection` 이다.
 * 그래서 호출부가 `entry.category` 를 넘기면 `protection` → 표에 없음 →
 * null 이 되어 **검토 필수 두 건이 통째로 사라졌다.** 방향이 "검토 안 해도
 * 된다" 쪽이라 위험하다.
 *
 * id 항목은 그대로 두고(그 계산기 하나를 콕 집어 묻는 경우), 그것이 속한
 * category 항목을 더해 어느 쪽으로 물어도 요구가 살아 있게 했다.
 *
 * `substation` 을 어떻게 할지 미뤄 뒀었다. 다시 보니 물음이 틀렸다 —
 * **`requiresPEReview` 는 production 호출처가 0 이다**(2026-07-28 실측).
 * 어느 쪽으로 답하든 사용자에게 닿지 않는다. `arc-flash`·`grounding` 의
 * `required: true` 조차 아무 화면에도 안 뜬다. 이 표 전체가 휴면이고
 * 그 사실은 `docs/DORMANT_MANIFEST.md` 에 적었다(§2.5-②).
 *
 * 그래도 표는 맞게 둔다 — 배선하는 날 틀린 표를 켜지 않도록. 표 자신의
 * 기준선(**안전 관련 → PE 필수 / 설계 검증 → 기사**)을 그대로 적용하면
 * `substation` 은 카테고리 통째로 답할 수 없다. 섞여 있기 때문이다:
 * 수전 용량·CT·VT 선정은 설계 검증이고, **피뢰기 선정은 보호 기기 선정**
 * 이라 `protection`·`grounding` 과 같은 줄이다. 그래서 표의 기존 방식대로
 * (id 항목 + 카테고리 항목) 피뢰기만 id 로 집어 올린다.
 *
 * 나머지 카테고리(power·motor·lighting·renewable·global·ai)는 **비워 둔다** —
 * 검토가 필요한지는 제품·전문가 판단이고 코드 정리하다 정할 일이 아니다.
 */
export const REVIEW_REQUIREMENTS: ReviewRequirement[] = [
  { category: 'arc-flash', required: true, reviewer: 'PE (전기)', reason: '안전 관련 — IEEE 1584 적합성 검증 필수' },
  { category: 'short-circuit', required: true, reviewer: 'PE (전기)', reason: '보호 협조 — 차단 용량 검증 필수' },
  // 위 둘이 속한 카테고리. 이 줄이 없으면 category 로 물을 때 요구가 사라진다.
  { category: 'protection', required: true, reviewer: 'PE (전기)', reason: '안전·보호 협조 — 아크플래시 입사에너지와 차단 용량 검증 필수' },
  { category: 'grounding', required: true, reviewer: 'PE (전기)', reason: '안전 관련 — 현장 측정 병행 필수' },
  { category: 'voltage-drop', required: false, reviewer: '전기 기사', reason: '설계 검증 — 서류 검토로 충분' },
  { category: 'cable-sizing', required: false, reviewer: '전기 기사', reason: '설계 검증 — 보정계수 확인' },
  // `cable-sizing` 이 속한 카테고리 — 같은 요구를 카테고리 조회에도 건다.
  { category: 'cable', required: false, reviewer: '전기 기사', reason: '설계 검증 — 보정계수 확인' },
  { category: 'transformer', required: false, reviewer: '전기 기사', reason: '용량 산정 — 부하 데이터 확인' },
  // 피뢰기는 보호 기기 선정이다 — 정격이 낮으면 뇌서지에 스스로 파괴되고,
  // 높으면 보호가 안 된다. 표의 기준선상 `protection`·`grounding` 과 같은 줄.
  { category: 'surge-arrester', required: true, reviewer: 'PE (전기)', reason: '안전 관련 — 절연협조(보호여유도) 검증 필수' },
  // 카테고리도 필수다. 처음엔 '수전 용량·CT·VT 는 설계 검증' 이라 false 로
  // 뒀는데 기존 게이트가 잡았다 — 카테고리로 물으면 피뢰기 요구가 사라진다.
  // 조회 키가 하나뿐이라 카테고리 답이 id 답을 덮는다. 게이트가 옳다.
  // 도메인으로도 맞다: 이 제품의 대상은 154kV 급 수전설비이고, 국내에서
  // 수전설비 설계는 유자격 전기기술자의 영역이다.
  { category: 'substation', required: true, reviewer: 'PE (전기)', reason: '안전 관련 — 피뢰기 절연협조(보호여유도) 검증 + 수전설비 설계는 유자격자 영역' },
];

/** 면책조항 생성 */
export function getDisclaimer(language: string = 'ko'): ProfessionalDisclaimer {
  return DISCLAIMERS[language] ?? DISCLAIMERS['ko'];
}

/**
 * 불확실성 정보 조회 — id 우선, 없으면 카테고리로.
 *
 * 전에는 접미사 정규식으로 기본 id 를 뽑았다(`voltage-drop-3phase →
 * voltage-drop`). 그런데 **그 명명 규칙이 이 저장소에 없다** — 실제 id 는
 * `three-phase-vd`·`complex-voltage-drop`·`busbar-vd`·`country-compare-vd`
 * 라 정규식이 한 번도 안 걸렸다(2026-07-28 확인). 결과적으로 전압강하
 * 변형 4 종이 전부 null 이었고, 표의 `grounding` 키는 id 가 아니라
 * 카테고리라 접지 계산기 3 종도 전부 null 이었다.
 *
 * 정규식이 하려던 일이 곧 "변형을 기본 항목으로 모으기" 이므로, 그걸
 * 레지스트리가 이미 갖고 있는 **카테고리**로 한다. 여기서 레지스트리를
 * import 하면 상수↔계산기 순환이 생기므로 호출부가 넘긴다.
 */
export function getUncertainty(calculatorId: string, category?: string): UncertaintyInfo | null {
  return UNCERTAINTY[calculatorId] ?? (category ? UNCERTAINTY[category] ?? null : null);
}

/** 전문가 검토 필요 여부 */
export function requiresPEReview(calculatorCategory: string): ReviewRequirement | null {
  return REVIEW_REQUIREMENTS.find(r => r.category === calculatorCategory) ?? null;
}
